### ISSUE TITLE
Feature Engineering

### ISSUE THREAD

**Issue by ottofabian** [BoboDance/NLP4Web_Project#12]

**Comment by cbiehl** [comment]
Lexical diversity feature works well. Pay attention to necessary POS tagsets for other DKPro extractors.

**Comment by cbiehl** [comment]
DKPro TC's "ContextualityMeasureFeatureExtractor" also works very well! Use the OpenNLP tagger for the POS tags.

**Comment by ottofabian** [comment]
Duplicate of #4
