### ISSUE TITLE
Correct format of JSON

### ISSUE THREAD

**Issue by ottofabian** [BoboDance/NLP4Web_Project#23]
The current JSON returns a malformed JSON.
As a consequence, we cannot process the JSON with GSON. 
Please provide a valid json format (checked with: https://jsonlint.com)

**Comment by mrnyc54** [comment]
Implemented a valid JSON (checked with: https://jsonlint.com). Implementation mainly  from https://forum.processing.org/one/topic/saving-json-data-from-twitter4j.html  . Twitter4j uses Status Objects to represent the Tweets. Example code to restoe these from JSON is available as a comment in linked tutorial. Maybe it will become useful.
Also: JSON objects are way bigger than before (more than double size of previous folder). Probably some performance optimization potential there.
